//! In-process PlatformIO engine (M7) — the default `platformio` backend.
//!
//! Where [`crate::tools::pio`] shells out to an external Python `pio`, this module
//! drives the `platformio_rs` library in-process via
//! [`platformio_rs::commands::run::run_build`], so `nff compile`/`nff flash` and
//! the `compile`/`flash` MCP tools run the native ESP32 fast-path directly (no
//! subprocess). It reuses `pio`'s backend-agnostic scaffolding verbatim —
//! `resolve_project`, `write_platformio_ini`, `discover_artifacts`, `is_scaffolded`
//! — and only replaces *execution*. The legacy subprocess path stays reachable via
//! [`crate::tools::config::pio_legacy`]. Non-ESP32 families fall through to
//! `platformio_rs`'s SCons delegation automatically.

use std::path::Path;

use platformio_rs::cli::RunArgs;

use crate::tools::pio;
use crate::tools::toolchain::{ProcessStream, RunResult, ToolchainError};

/// The nff environment name generated by [`pio::write_platformio_ini`].
const ENV: &str = "nff";

/// Point `platformio_rs`'s SCons delegation at a Python that can `import
/// platformio` (PlatformIO's penv), unless the user already set `PYTHONEXEPATH`.
/// The native engine needs this only on a cache-miss capture build (the hot replay
/// path is pure Rust). Idempotent; a concurrent set to the same value is benign.
fn ensure_python_env() {
    if std::env::var_os("PYTHONEXEPATH").is_none_or(|v| v.is_empty()) {
        if let Some(py) = pio::platformio_python() {
            std::env::set_var("PYTHONEXEPATH", py);
        }
    }
}

/// Build the `platformio_rs` run arguments for a resolved project. `native = true`
/// forces the native fast-path for supported ESP32 families. Scaffolds pin `-e nff`
/// (their fixed env); BYO projects build their own configured envs.
fn run_args(project_dir: &Path, upload: bool, port: Option<&str>) -> RunArgs {
    RunArgs {
        environment: if pio::is_scaffolded(project_dir) { vec![ENV.into()] } else { vec![] },
        target: if upload { vec!["upload".into()] } else { vec![] },
        project_dir: project_dir.display().to_string(),
        upload_port: port.map(str::to_string),
        native: true,
        ..Default::default()
    }
}

/// Run an in-process build, mapping the outcome into a [`RunResult`] (captured
/// output as stdout, exit code preserved).
fn build(project_dir: &Path, upload: bool, port: Option<&str>) -> Result<RunResult, ToolchainError> {
    let report = platformio_rs::commands::run::run_build(&run_args(project_dir, upload, port))
        .map_err(|e| ToolchainError::Invalid(e.to_string()))?;
    Ok(RunResult {
        success: report.code == 0,
        stdout: report.output,
        stderr: String::new(),
        returncode: report.code,
    })
}

/// Compile a resolved pio project natively (no upload). Mirrors
/// [`pio::compile_sketch`]'s signature/return so `toolchain::compile_only` can swap
/// engines transparently.
pub fn compile_sketch(project_dir: &Path, board: &str) -> Result<RunResult, ToolchainError> {
    ensure_python_env();
    pio::write_platformio_ini(project_dir, board)?;
    build(project_dir, false, None)
}

/// A live-streaming compile (build only). The native build runs in-process and its
/// captured output is emitted as lines — behaviorally identical to the subprocess
/// stream, which already buffers before emitting.
pub fn stream_compile(project_dir: &Path, board: &str) -> Result<ProcessStream, ToolchainError> {
    ensure_python_env();
    pio::write_platformio_ini(project_dir, board)?;
    let args = run_args(project_dir, false, None);
    Ok(ProcessStream::in_process(move || match platformio_rs::commands::run::run_build(&args) {
        Ok(r) => (r.code, r.output, String::new()),
        Err(e) => (-1, String::new(), format!("ERROR: {e}")),
    }))
}

/// A live-streaming upload. Runs the native build with an `upload` target: the
/// prior [`stream_compile`] warmed the cache, so this recompiles nothing and the
/// native replay flashes via the captured `esptool write_flash` (port overridden).
pub fn stream_upload(project_dir: &Path, board: &str, port: &str) -> Result<ProcessStream, ToolchainError> {
    ensure_python_env();
    pio::write_platformio_ini(project_dir, board)?;
    let args = run_args(project_dir, true, Some(port));
    Ok(ProcessStream::in_process(move || match platformio_rs::commands::run::run_build(&args) {
        Ok(r) => (r.code, r.output, String::new()),
        Err(e) => (-1, String::new(), format!("ERROR: {e}")),
    }))
}

/// Compile then flash a resolved pio project in a single native run (the replay
/// builds + flashes when the target is `upload`). Returns the same `OK:`/`ERROR:`
/// string shape as [`pio::flash_project`] for the `flash` MCP tool.
pub fn flash_project(project_dir: &Path, board: &str, port: &str) -> String {
    ensure_python_env();
    if let Err(e) = pio::write_platformio_ini(project_dir, board) {
        return format!("ERROR: {e}");
    }
    match build(project_dir, true, Some(port)) {
        Ok(r) if r.success => {
            let mut sections = vec!["OK: flash complete".to_string()];
            let out = r.output();
            if !out.is_empty() {
                sections.push(format!("--- build ---\n{out}"));
            }
            sections.join("\n")
        }
        Ok(r) => format!("ERROR: Build/upload failed (exit {}):\n{}", r.returncode, r.output()),
        Err(e) => format!("ERROR: {e}"),
    }
}
